# すでに存在するトンネルを使う
#UseSSH: false
#DBサーバーのホスト名、指定しなければlocalhost
DBhost: ${DBHOST}
DBport: ${DBPORT}
# データベース名
DBname: ENC[AES256_GCM,data:6IB7IqwmvJQ=,iv:NAwpuFx+qlIA+T72VvCMY/ZSLQYtc6CbYTXAX17RHjg=,tag:/xVH1RCNC+71dgzm1flzGw==,type:str]
#
# ログイン名とパスワードは環境変数で渡す
DBuser: ENC[AES256_GCM,data:TRvj9xGm9g==,iv:ajHQsAzaHNhIICNjh0LMYk3QJR7PWcd6knoiMVezK5M=,tag:szUPeCHRG57iqr+ghQEfdQ==,type:str]
DBpswd: ENC[AES256_GCM,data:Uaepzes1IhpB32U=,iv:019jVl/Upw8MQIvMrHTUujkcWkm2dD4OLv6dvmdD02M=,tag:eEgnHt4CVRyARaf6neucAQ==,type:str]
# SSH接続を使わない
UseSSH: false
# SSH接続を使う
#UseSSH: true
SSHhost: ${SSHHOST}
SSHport: ${SSHPORT}
SSHuser: ${SSHUSER}
#SSHpswd: ${SSHPSWD}
SSHprvkey: ${SSHPRVKEY}
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5RnV3TDRVSkFpUVR4TUd6
            VjVPSXpoODVtT2c0WUZhdmR3SHlsVXJHQmhjCnFYdWJlM2ZvRjFoOFRDR1oyKzBC
            YWFtanZFTXFzMnQramhZSXJhOHR1MUEKLS0tIGJJR3UvQTdHT3VSdVN3M3ZRQ3RR
            Q0d3OHZIVzkwbDBFZkxPTnhCR2R5ZUkKewc3SLqnnT1e7nG/HR8IuxyBb1L8VUf1
            paIIaEq5ywBhNM7Bxa705p1G/vCbqPNfWeRMtDBuoFS67/83Q/EdSA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13mlf945e3emk75ys348xttw048ufq7vpgw7l94g63tl5pt03mdrsfqra2l
    encrypted_regex: ^(apikey|SRuser|SRpswd|DBuser|DBpswd|DBname|TurnstileSiteKey|TurnstileSecretKey|IPEncryptionKeyHex|sr_acct|sr_pswd)$
    lastmodified: "2026-10-07T06:45:52Z"
    mac: ENC[AES256_GCM,data:bHh5I3+EME4Iu87cQvFnlg9JN4JW1+wBwkwMiQC5flymve5pwm4QIO765Bw7ESm2flCcTMdFQr+P8agvYoGCwPDS77YBd9GHiS7FUteLpIoL35jJcgL9ZhXVY2znd4wG2qhoodwzt9czAzphuIXNDbKbmv5MCFdgfZsGm/uW07Y=,iv:lyBy9xxkoHAwhgvoULzxVgcFikmThFiCTwzKPc5gDFE=,tag:wSE0BNKKM+77XNEf6Z0gtw==,type:str]
    version: 3.13.3
