## CGIとして動作させるときのWebサーバを指定する。
## WebServer nginxSakura, Apache2Ubuntu or None
## NoneはこのプログラムをWebサーバとして動作させる。
## この設定はグラフを作るときSVGファイルをどこに置くかということに関係する。
## グラフを出力しないケースではどのような設定にしても問題ないでしょう。
WebServer: None
# HTTPport: 8080
HTTPport: 8000
# Cloudflare Turnstile設定
TurnstileSiteKey: ENC[AES256_GCM,data:aul0P38ewYzmC1UScbovH2ktkYeAQK4Q,iv:xVrtSO+zQEdg5+X5EyQJAZOBS4vTBJMJQe5vz4ELPkI=,tag:tyBbDMXPwvY7If6VgBHZYg==,type:str]
TurnstileSecretKey: ENC[AES256_GCM,data:905fiYbl+pRFkF4cc0rBCLY1rQYqLNBvD3OmcN/+Ol4na+Q=,iv:nvDqbd2X/RcCfYvDF3ANcVOZAXEFm+Gb9e+Lm3eU+r8=,tag:gvSRFb0pZ2xOkg7f3tDYig==,type:str]
# Turnstileセッション管理
TurnstileUseSession: true # セッション機能の有効/無効
TurnstileSessionDuration: 1800 # セッション有効期間（秒）デフォルト1時間
TurnstileSessionMaxUses: 0 # セッション内の最大利用回数（0=無制限）
# SSLに関する設定は環境変数で渡す。
## CGIとして実行するときあるいはSSLを使用せずWebServerとして実行するときは設定しない。
## SSL証明書関連のファイルはふつうrootしか参照できない形でおかれているので
## その対策が必要です。
## 今は~/.letsencrypt にコピーしてきて使っていますが...
SSLcrt: null
SSLkey: null
# イベント一覧に表示するイベントの数（緊急対応でここに）
NoEvent: 30
# メンテナンスに際して機能を停止し、メンテナンス中であることを表示する
#Maintenance: true
#
# ボットの排除レベル
LvlBots: 3
# 時間枠のアクセス回数上限
AccessLimit: 3
# アクセス回数制限の時間枠(秒単位)
TimeWindow: 1
# IPアドレス暗号化キー
IPEncryptionKeyHex: ENC[AES256_GCM,data:sOWcWUpPmY4h5qX21LPAPKRWIhdyt+7RAJtXPVRltt8sZc5zgTIRDi/gSzAS3nragIUg6c22ThzmIWZwDlbQ0Q==,iv:C4QHX8oulrXuCDjeBzsrD9qyVBJ2kmkI8EKda6Vn+b4=,tag:se3AEQRM/0YJ2w3jgLSJFg==,type:str]
# IPアドレスによるアクセス制限を行うか？
DenyNonJP: false
# ユーザー情報登録のエンドポイント
GWURL: http://localhost:8888/
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxQU5ZUitkTWlnTFpMS0lt
            UzhIR1JLQlVZdUdQaHBEVlVxYVFNL1BUUzE4CmtqcHRHYU9PM1N2d2R0N2pSWWRl
            Zy9uQVFkbWh5VnFPWnZzNVcrOXNMWjgKLS0tIC8rKzFMVDhLek1GN3o2K01iS3Bv
            U1NXZzVXYjFPZ2VxQmpmRGhDTkxCelkKo6OyhunmpN3wZdGw5Y7JtYayFu1zojGX
            K9LhxdlHPRBOdMF2bDuwDO6pRRH24InvXMpLGxTtFeL/sDXeqi1KPA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13mlf945e3emk75ys348xttw048ufq7vpgw7l94g63tl5pt03mdrsfqra2l
    encrypted_regex: ^(apikey|SRuser|SRpswd|DBuser|DBpswd|DBname|TurnstileSiteKey|TurnstileSecretKey|IPEncryptionKeyHex|sr_acct|sr_pswd)$
    lastmodified: "2026-09-14T05:26:10Z"
    mac: ENC[AES256_GCM,data:qJQrPuWi0IEwlfJ8Og9b5qdriRlCEjnhBbIV4uf4/2URxnF4dftEZYF6PqEnieWV2HSUxH9vMMmMWChN/egw+kAc2QpgtJrtiIowOQltBX3TPtU+2IDaFrCRXsJDFTjVr/cO+mYoWmbzSbf98ML8N+vssSCGi7/IulJ8l+N6bSI=,iv:XCJeQZpI9mJ5lMlBwrozWhbcNgl9F6cBQRUq8AhSFTE=,tag:Hj5WBm+Bb6oH+eVLEJ1oXw==,type:str]
    version: 3.13.1
